Iter9
ArtemShalinFe/metcoll pull request #10
Opened 2023-05-23 07:02 UTC by ArtemShalinFe

2023-05-23 21:28 UTC, s-shpak requested changes

2023-05-23 21:28 UTC, s-shpak commented on go.sum
Нужно обновить при помощи `go mod tidy`

2023-05-23 21:28 UTC, s-shpak commented on cmd/agent/main.go
Не могу оставить коммент к той строке, но нет смысла создавать новый клиент внутри этого `if`

2023-05-23 21:28 UTC, s-shpak commented on cmd/agent/main.go
> +		time.Sleep(pause)
Почему ты решил перенести это ожидание в начало цикла? Раньше было логичнее

2023-05-23 21:28 UTC, s-shpak commented on cmd/agent/main.go
> +	Update(j json.Marshaler) error
Нет смысла требовать, чтобы значение удовлетворяло `json.Marshaler`: тип метрики в любом случае можно представить в виде JSON

2023-05-23 21:28 UTC, s-shpak commented on internal/logger/logger.go
> +		return nil, err
Сторонние ошибки лучше оборачивать

2023-05-23 21:28 UTC, s-shpak commented on internal/logger/logger.go
> +	defer l.Sync()
Зачем этот вызов? Он будет выполнен при выходе из конструктора, что не нужно

2023-05-23 21:28 UTC, s-shpak commented on internal/logger/logger.go
> +		start := time.Now()
`time.Now` лучше вызывать непосредственно перед `ServeHTTP`

2023-05-23 21:28 UTC, s-shpak commented on internal/logger/responseData.go
файлы в Go надо называть через snake-case

2023-05-23 21:28 UTC, s-shpak commented on cmd/agent/main.go
> +	log.Printf("Parsed agent config: %+v", cfg)
Почему бы на агенте не использовать тот же логгер, что и на сервере?

2023-05-23 21:28 UTC, s-shpak commented on cmd/server/main.go
> +	log.Printf("Parsed server config: %+v", cfg)
Если ты используешь zap, то есть смысл использовать его везде: не надо держать несколько разных логгеров

2023-05-23 21:28 UTC, s-shpak commented on internal/compress/compressWriter.go
> +	w    http.ResponseWriter
Это поле можно "встроить" в `CompressWriter`, чтобы не определять `Header()` явно

2023-05-23 21:28 UTC, s-shpak commented on internal/handlers/handlers.go
> +type stateSaver interface {
Это не очень хороший дизайн: если мы уже сохраняем данные в store, то не надо делать это два раза. Подумай, как можно реализовать `FileStorage` так, чтобы это было неизвестно этому слою

2023-05-23 21:28 UTC, s-shpak commented on internal/metcoll/metcoll.go
> +	req, err := http.NewRequest(http.MethodPost, fmt.Sprintf("http://%s/update/", c.host), &zBuf)
URL лучше соединять при помощи https://pkg.go.dev/net/url#JoinPath

2023-05-23 21:28 UTC, s-shpak commented on internal/metrics/metrics.go
> +func (m *Metrics) UnmarshalJSON(b []byte) error {
`UnmarshalJSON` и `MarshalJSON` в данном случае не нужны (или я ошибаюсь)?

2023-05-23 21:28 UTC, s-shpak commented on internal/storage/storage.go
> +func (ms *MemStorage) MarshalJSON() ([]byte, error) {
Похоже, что эта функция не нужна (или я ошибаюсь?)

2023-05-24 15:39 UTC, ArtemShalinFe commented on go.sum
Готово. А как можно понять, что нужно обновить при помощи `go mod tidy`, если IDE не ругается и ничего не пишет...

2023-05-24 15:42 UTC, ArtemShalinFe commented on cmd/agent/main.go
Вынес из `if` и из `for`.

2023-05-24 15:43 UTC, ArtemShalinFe commented on cmd/agent/main.go
> +		time.Sleep(pause)
Это после борьбы с автотестами осталось. Мне тоже нравилось больше, когда было в конце цикла - поправил.

2023-05-24 15:51 UTC, ArtemShalinFe commented on cmd/agent/main.go
> +	Update(j json.Marshaler) error
Заменил на явное указание типа `*metrics.Metrics`

Не хотелось добавлять зависимость этого пакета от пакета `metrics` - поэтому `json.Marshaler` вписал.

2023-05-24 16:06 UTC, ArtemShalinFe commented on internal/logger/logger.go
> +	defer l.Sync()
Перенес вызов в main функцию сервера.

2023-05-24 16:07 UTC, ArtemShalinFe commented on internal/logger/logger.go
> +		start := time.Now()
Спасибо, перенес.

2023-05-24 16:08 UTC, artemshalin commented on internal/logger/responseData.go
Переименовал.

2023-05-24 16:22 UTC, ArtemShalinFe commented on cmd/agent/main.go
> +	log.Printf("Parsed agent config: %+v", cfg)
И правда! Спасибо, исправил.

2023-05-24 16:32 UTC, artemshalin commented on cmd/server/main.go
> +	log.Printf("Parsed server config: %+v", cfg)
Заменил. 
А что делать, если не удается инициализировать сам логгер? Как в таком случае, без стандартного логера, сохранить ошибку?

2023-05-24 16:42 UTC, ArtemShalinFe commented on internal/compress/compressWriter.go
> +	w    http.ResponseWriter
Попробовал исправить, а IDE меня поругала за `infinite recursive call` для функции `(c *CompressWriter) WriteHeader`.

2023-05-24 16:54 UTC, ArtemShalinFe commented on internal/logger/logger.go
> +		return nil, err
Я правильно понял, что здесь нужно написать что-то типа: 

`return nil, fmt.Errorf("cannot init zap-logger err: %v ", err)`

Чтобы понятнее было где именно ошибка произошла?

2023-05-24 16:55 UTC, ArtemShalinFe commented on internal/metcoll/metcoll.go
> +	req, err := http.NewRequest(http.MethodPost, fmt.Sprintf("http://%s/update/", c.host), &zBuf)
Спасибо! Поправил.

Эти бы знания, да на первых инкрементах 😄

2023-05-24 16:59 UTC, ArtemShalinFe commented on internal/metrics/metrics.go
> +func (m *Metrics) UnmarshalJSON(b []byte) error {
Я хотел сделать проверку корректности типа метрики во время маршалинга, демаршалинга, чтобы потом не проверять везде.

Только вот из-за этого кода написал:
```
if am.MType != CounterMetric && am.MType != GaugeMetric {
    return errUnknowMetricType
}
```

2023-05-24 17:00 UTC, ArtemShalinFe commented on internal/storage/storage.go
> +func (ms *MemStorage) MarshalJSON() ([]byte, error) {
Написал функцию, чтобы сделать проверку корректности типа метрики во время маршалинга, чтобы потом не проверять везде.

Только вот из-за этого кода написал:
```
if am.MType != CounterMetric && am.MType != GaugeMetric {
    return nil, errUnknowMetricType
}
```

2023-05-24 19:41 UTC, ArtemShalinFe commented on internal/compress/compressWriter.go
> +	w    http.ResponseWriter
Спасибо - получилось.

2023-05-24 20:40 UTC, artemshalin commented on internal/handlers/handlers.go
> +type stateSaver interface {
Для `Handlers`  сделал интерфейс `Storage`.
Переопределил методы, которые изменяют данные у типа `MemStorage`, в типе `FileStorage`. Добавил синхронную запись в файл.
В `Handlers` теперь в зависимости от конфига передается либо `MemStorage`, либо `FileStorage`. 
`Handlers` теперь ничего не известно о storage.

2023-05-26 08:45 UTC, s-shpak commented on go.sum
Я не уверен, что какие-то IDE это делают, т.к. в данном случае, похоже, вышла новая минорная версия зависимости, и ее надо было бампнуть. Для того, чтобы это детектить, надо переодически проводить аудит зависимостей, и запуск `go mod tidy` - самый простой способ

2023-05-26 08:47 UTC, s-shpak commented on go.sum
См. здесь про `go mod tidy`: https://go.dev/blog/migrating-to-go-modules

2023-05-26 11:45 UTC, s-shpak commented on cmd/agent/main.go
> +	Update(j json.Marshaler) error
В принципе, я не вижу проблем с зависимостями: все довольно логично, клиент апдейтит БД посылая туда метрики. 

Если же в другом случае тебе будет нужно отвязать эту зависимость от пакета, то передавать `any` - один из возможных вариантов (голые интрефейсы - не очень хорошая практика, но немногим хуже - а в чем-то и лучше -, чем `json.Marshaler`

2023-05-26 11:46 UTC, s-shpak commented on internal/logger/logger.go
> +		return nil, err
Да, именно

2023-05-26 11:50 UTC, s-shpak commented on cmd/server/main.go
> +	log.Printf("Parsed server config: %+v", cfg)
В этом случае можно прибегнуть либо к стандартному логгеру, либо к глобальному логгеру в `zap`: https://pkg.go.dev/go.uber.org/zap#L

2023-05-26 11:51 UTC, s-shpak commented on internal/metcoll/metcoll.go
> +	req, err := http.NewRequest(http.MethodPost, fmt.Sprintf("http://%s/update/", c.host), &zBuf)
:) Но я же, вроде, комментил это на первом спринте? Или я забыл?

2023-05-26 11:52 UTC, s-shpak commented on internal/metrics/metrics.go
> +func (m *Metrics) UnmarshalJSON(b []byte) error {
Кажется, что эта проверка не должна находиться в логике парсинга: парсинг относится скорее к транспортному слою, а валидация типов - к бизнес-логике

2023-05-26 11:53 UTC, s-shpak commented on internal/storage/storage.go
> +func (ms *MemStorage) MarshalJSON() ([]byte, error) {
См. выше

2023-05-26 12:23 UTC, s-shpak requested changes

2023-05-26 12:23 UTC, s-shpak commented on internal/compress/compressReader.go
snake-case

2023-05-26 12:23 UTC, s-shpak commented on internal/compress/compressWriter.go
snake-case

2023-05-26 12:23 UTC, s-shpak commented on internal/handlers/handlers.go
> +type stateSaver interface {
Очень круто! Давай теперь еще немного улучшим

2023-05-26 12:23 UTC, s-shpak commented on cmd/server/main.go
> +		fs, err := filestorage.NewFilestorage(s, l, cfg.FileStoragePath, cfg.StoreInterval, cfg.Restore)
Эту логику можно перенести в пакет `storage`: чтоьы функция там, на основании объекта конфигурации, принимала решение о создании того или иного стора. Эта та самая редкая ситуация, когда мы можем вернуть интерфейс из функции. Гипотетически, можно использовать и дженерики, но 1. мы это будем проходить дальше 2. дженерики могут повлиять на производительность, потому лучше эксперементировать с ними, когда у тебя есть какие-то бенчмарки

2023-05-26 12:23 UTC, s-shpak commented on cmd/server/main.go
> +func runGracefullInterrupt(l *logger.AppLogger, i *interrupter.Interrupters) {
В принципе, подойдет, но если хочешь сделать совсем хорошо, то надо бы еще завершить работу сервера прежде чем закрывать остальное

2023-05-26 12:23 UTC, s-shpak commented on internal/logger/logger.go
> +		return nil, fmt.Errorf("cannot init zap-logger err: %v ", err)
Можешь не делать это сейчас, но ошибки надо оборачивать при помощи `%w`

2023-05-26 12:23 UTC, s-shpak commented on internal/logger/logger.go
> +		return fmt.Errorf("cannot flush buffered log entries err: %v", err)
Ты же на маке? Запустил код у себя, столкнулся с проблемой, описанной здесь: https://github.com/uber-go/zap/issues/328

Если коротко, то самое простое решение - просто игнорить ошибку из `Sync`. Можно написать ОС-зависимый код для LoggerInterrupt, но необязательно

2023-05-26 12:23 UTC, s-shpak commented on internal/compress/compress.go
> +		if strings.Contains(acceptEncoding, "gzip") {
Как обработать ситуацию, когда агент принимает несколько "кодировок" ?

2023-05-26 12:23 UTC, s-shpak commented on internal/filestorage/filestorage.go
> +func (fs *Filestorage) FilestorageInterrupt() error {
Нет смысла дублировать название структуры в префиксе имени функции

2023-05-28 09:32 UTC, ArtemShalinFe commented on internal/storage/storage.go
> +func (ms *MemStorage) MarshalJSON() ([]byte, error) {
Перенес логику в бизнес-логику

2023-05-28 09:32 UTC, ArtemShalinFe commented on internal/metrics/metrics.go
> +func (m *Metrics) UnmarshalJSON(b []byte) error {
Перенес проверку типа в бизнес-логику

2023-05-28 09:33 UTC, ArtemShalinFe commented on internal/compress/compressReader.go
поправил

2023-05-28 09:33 UTC, ArtemShalinFe commented on internal/compress/compressWriter.go
поправил

2023-05-28 09:51 UTC, ArtemShalinFe commented on cmd/server/main.go
> +func runGracefullInterrupt(l *logger.AppLogger, i *interrupter.Interrupters) {
Протянул в функцию http.Server. Добавил вызов Shutdown в начало.

2023-05-28 09:55 UTC, ArtemShalinFe commented on internal/logger/logger.go
> +		return nil, fmt.Errorf("cannot init zap-logger err: %v ", err)
Поправил, где увидел.

2023-05-28 09:58 UTC, ArtemShalinFe commented on internal/filestorage/filestorage.go
> +func (fs *Filestorage) FilestorageInterrupt() error {
поправил тут и в logger

2023-05-28 10:16 UTC, ArtemShalinFe commented on internal/logger/logger.go
> +		return fmt.Errorf("cannot flush buffered log entries err: %v", err)
Ого, а у меня нету такой штуки. Поправил, теперь возвращаем `nil` для mac os.

2023-05-28 13:45 UTC, ArtemShalinFe commented on internal/compress/compress.go
> +		if strings.Contains(acceptEncoding, "gzip") {
Исправил с `r.Header.Get("Accept-Encoding")` + `strings.Contains` на `r.Header.Values("Accept-Encoding")` + цикл обхода.

Я так понял, проблема такого написания в том, что не очень удобно расширять список возможных кодировок, а с если получать сразу массив, то:
- Есть какой-то пускай гипотетический приоритет, в котором нужно закодировать данные. 
- Приоритетом может управлять агент.

Что-то больше в голову ничего не приходит...

2023-05-31 07:22 UTC, ArtemShalinFe commented on cmd/server/main.go
> +		fs, err := filestorage.NewFilestorage(s, l, cfg.FileStoragePath, cfg.StoreInterval, cfg.Restore)
Поправил

2023-05-31 20:38 UTC, s-shpak commented on internal/compress/compress.go
> +		if strings.Contains(acceptEncoding, "gzip") {
Да, действительно нужно перебирать все хедеры, такое решение подойдет

2023-05-31 20:50 UTC, s-shpak approved these changes

2023-05-31 20:50 UTC, s-shpak commented on internal/handlers/handlers.go
> +	h.logger.Info("Metric was updated - ", m.ID, " new value: ", m.String())
В таких случаях лучше исползовать `Infof`

2023-05-31 20:50 UTC, s-shpak commented on internal/stats/stats.go
> +	gaugeMetrics["Alloc"] = metrics.NewGaugeMetric("Alloc", float64(s.memStats.Alloc))
Я бы делал это в цикле

2023-05-31 20:50 UTC, s-shpak commented on internal/storage/filestorage.go
> +		fs.logger.Error("cannot open or creating file for state loading err: ", err)
Не очень понимаю, зачем здесь логировать ошибку: в Го и так на обработку ухоит много строк кода, но теперь к каждой ошибке добавяется еще и логрование. Я бы прокидывал ошибку максимально наверх и только там бы централизованно логировал

2023-05-31 20:50 UTC, s-shpak commented on internal/storage/filestorage_test.go
> +				path:          "/tmp/tests-state-save-storage-1.json",
Чтобы было совсем чисто можно использовать `https://pkg.go.dev/os#CreateTemp` и `test.TempDir`

2023-06-01 06:34 UTC, artemshalin commented on internal/storage/filestorage_test.go
> +				path:          "/tmp/tests-state-save-storage-1.json",
Поправил. Спасибо!

2023-06-01 07:13 UTC, ArtemShalinFe commented on internal/handlers/handlers.go
> +	h.logger.Info("Metric was updated - ", m.ID, " new value: ", m.String())
Угу, поправил. Спасибо

2023-06-01 07:14 UTC, ArtemShalinFe commented on internal/storage/filestorage.go
> +		fs.logger.Error("cannot open or creating file for state loading err: ", err)
Спасибо, потихоньку начинаю понимать - что, зачем и почему именно так)

2023-06-01 08:00 UTC, artemshalin commented on internal/stats/stats.go
> +	gaugeMetrics["Alloc"] = metrics.NewGaugeMetric("Alloc", float64(s.memStats.Alloc))
Переписал через цикл и `switch case`

2023-06-04 11:21 UTC, s-shpak approved these changes

2023-06-05 05:43 UTC, merged