Iter13
ArtemShalinFe/metcoll pull request #14
Opened 2023-06-10 15:30 UTC by ArtemShalinFe

2023-06-16 12:51 UTC, s-shpak requested changes

2023-06-16 12:51 UTC, s-shpak commented on cmd/agent/main_test.go
>  	return nil
Если тест пока ничего не делает, то лучше просто его удалить

2023-06-16 12:51 UTC, s-shpak commented on internal/handlers/handlers.go
> +	h.logger.Infof("BatchUpdate body: %s", string(b))
Не стоит логировать это сообщение на уровне `Info`, `Debug` должно хватить

2023-06-16 12:51 UTC, s-shpak commented on internal/handlers/handlers.go
> +	if _, err = w.Write(b); err != nil {
Не совсем понимаю зачем отправлять пользователю ошибки: что если они внутренние?

2023-06-16 12:51 UTC, s-shpak commented on internal/handlers/handlers.go
> +		h.logger.Errorf("Ping error: %w", err)
Логгер не умеет обрабатывать `%w`. То что vscode не находит эту проблему - еще один аргумент за то, чтобы использовать напрямую логгер, а не интерфейс

2023-06-16 12:51 UTC, s-shpak commented on internal/handlers/handlers_test.go
> +	s, _ := storage.InitStorage(ctx, cfg, l)
Ошибки надо проверять и в тестах

2023-06-16 12:51 UTC, s-shpak commented on internal/handlers/router.go
> +		rctx, cancel := context.WithCancel(ctx)
Это плохая идея, забирай лучше контекст из `r.Context()` (и можно пока не создавать новый контекст, т.к. ты все равно нигде не вызываешь `cancel`)

2023-06-16 12:51 UTC, s-shpak commented on internal/logger/logger.go
> +		l.Infof("HTTP request method:%s, url:%s, duration:%s, statusCode:%d, responseSize: %d",
```suggestion
		l.Infof("HTTP request method: %s, url: %s, duration: %s, statusCode: %d, responseSize: %d",
```

2023-06-16 12:51 UTC, s-shpak commented on internal/metcoll/client.go
> +func retryHTTPrequest(f Func, req *http.Request, ss Sleeper) (*http.Response, error) {
Не стоит ретраить запрос бесконечно (тем более рекурсивно). Посмотри как это реализовано в https://github.com/hashicorp/go-retryablehttp (можешь, кстати, использовать эту библиотеку)

2023-06-16 12:51 UTC, s-shpak commented on internal/sleepstepper/sleepstepper.go
> +func NewSleepStepper(sleep int, step int, maxSleep int) *SleepSteper {
Посмотри как это реализовано здесь: https://github.com/avast/retry-go, можешь использовать эту библиотеку или заимплементить твое решение похожим образом

2023-06-16 12:51 UTC, s-shpak commented on internal/stats/stats.go
> +			return float64(c[0].Mhz), true
А что содержит поле `Mhz`? Частоту процессора?

2023-06-16 12:51 UTC, s-shpak commented on internal/stats/stats.go
> +		vm, err := mem.VirtualMemory()
Ты уверен, что мы не можем получить эту метрику без использования внешней билблиотеки?

2023-06-16 12:51 UTC, s-shpak commented on internal/storage/database_storage.go
> +		return fmt.Errorf("cannot create counter table err : %w", err)
Транзакцию надо откатить в случае ошибки

2023-06-16 12:51 UTC, s-shpak commented on internal/storage/database_storage.go
> +			return val, false
Почему бы не возвращать ошибку из этой функции?

2023-06-16 12:51 UTC, s-shpak commented on internal/storage/database_storage.go
> +	row, err := s.QueryRowContext(rctx, q, key, val)
Это не `Query`, это должен быть `Exec`

2023-06-16 12:51 UTC, s-shpak commented on internal/storage/database_storage.go
> +	val, _ := s.GetInt64Value(ctx, key)
Получение значения можно делать либо внутри транзакции, либо без дополнительного запроса (посмотри как работает  `ON CONFLICT`)

2023-06-16 12:51 UTC, s-shpak commented on internal/storage/filestorage.go
> +func retryOpenFile(f OpenFileFunc, ss Sleeper, name string, flag int, perm fs.FileMode) (*os.File, error) {
Кажется, что использование retry здесь - оверкил

2023-06-16 12:51 UTC, s-shpak commented on internal/storage/storage.go
> +func (ms *MemStorage) GetFloat64Value(ctx context.Context, key string) (float64, bool) {
```suggestion
func (ms *MemStorage) GetFloat64Value(_ context.Context, key string) (float64, bool) {
```

2023-06-16 12:51 UTC, s-shpak commented on internal/handlers/handlers.go
> +		if err := m.Update(ctx, h.values); err != nil {
Сейчас ты делаешь столько запросов к БД, сколько у тебя метрик. Ты можешь посылать все одним запросом

2023-06-17 15:00 UTC, ArtemShalinFe commented on internal/handlers/handlers.go
> +	h.logger.Infof("BatchUpdate body: %s", string(b))
Поправил

2023-06-17 15:01 UTC, ArtemShalinFe commented on cmd/agent/main_test.go
>  	return nil
Заменить на моки

2023-06-17 15:07 UTC, ArtemShalinFe commented on internal/handlers/handlers.go
> +	if _, err = w.Write(b); err != nil {
Поправил

2023-06-17 15:07 UTC, ArtemShalinFe commented on internal/handlers/handlers.go
> +		h.logger.Errorf("Ping error: %w", err)
Отказался от интерфейса в пользу явного использования объекта

2023-06-17 15:09 UTC, ArtemShalinFe commented on internal/handlers/handlers_test.go
> +	s, _ := storage.InitStorage(ctx, cfg, l)
Поправил

2023-06-17 15:11 UTC, ArtemShalinFe commented on internal/handlers/router.go
> +		rctx, cancel := context.WithCancel(ctx)
Поправил

2023-06-17 16:01 UTC, ArtemShalinFe commented on internal/metcoll/client.go
> +func retryHTTPrequest(f Func, req *http.Request, ss Sleeper) (*http.Response, error) {
Поправил. Прикрутил еще логгер приложения к этой библиотеке, но пришлось в типе `AppLogger` использовать не встраивание, а композицию. Подумал, что наверно подменять методы - плохо.

2023-06-17 16:05 UTC, ArtemShalinFe commented on internal/sleepstepper/sleepstepper.go
> +func NewSleepStepper(sleep int, step int, maxSleep int) *SleepSteper {
Перешел на библиотеку.

2023-06-17 16:06 UTC, ArtemShalinFe commented on internal/storage/database_storage.go
> +		return fmt.Errorf("cannot create counter table err : %w", err)
Добавил в `defer tx.Rollback(ctx)` в самом начале метода

2023-06-17 16:08 UTC, ArtemShalinFe commented on internal/storage/database_storage.go
> +			return val, false
Изменил интерфейс, изменил database_storage. Теперь возвращают ошибки.

2023-06-17 16:08 UTC, ArtemShalinFe commented on internal/storage/database_storage.go
> +	row, err := s.QueryRowContext(rctx, q, key, val)
заменил `database/sql` на `pgx`

2023-06-17 16:09 UTC, ArtemShalinFe commented on internal/storage/database_storage.go
> +	val, _ := s.GetInt64Value(ctx, key)
исправил запросы, добавил sub-select

2023-06-17 16:09 UTC, ArtemShalinFe commented on internal/storage/filestorage.go
> +func retryOpenFile(f OpenFileFunc, ss Sleeper, name string, flag int, perm fs.FileMode) (*os.File, error) {
убрал

2023-06-17 16:16 UTC, ArtemShalinFe commented on internal/handlers/handlers.go
> +		if err := m.Update(ctx, h.values); err != nil {
заменил database/sql на pgx и вроде бы, разобрался как работать с Batch.

2023-06-19 12:09 UTC, ArtemShalinFe commented on internal/stats/stats.go
> +			return float64(c[0].Mhz), true
Ага, если библиотеке верить.

2023-06-19 12:10 UTC, ArtemShalinFe commented on internal/stats/stats.go
> +		vm, err := mem.VirtualMemory()
Гуглил. На сколько понимаю для unix берут из одного места - /proc/meminfo, а для вин костыли на С пишут. А как еще можно?

2023-06-20 11:43 UTC, s-shpak commented on cmd/agent/mock/main.go
Не стоит создавать отдельный пакет для моков, их кладут в один пакет с тестами, как правило

2023-06-20 11:43 UTC, s-shpak commented on internal/handlers/handlers.go
> +	// Автотесты хотят, чтобы мы возвращали ошибку изменения каждой метрики
Не сомг найти это требование в ТЗ, ты не мог бы сослаться, пожалуйста?

2023-06-20 11:43 UTC, s-shpak commented on internal/handlers/handlers.go
> +	if _, err = w.Write(b); err != nil {
Пока не понял, пользователю все равно улетают сообщения об ошибках

2023-06-20 11:43 UTC, s-shpak commented on internal/handlers/handlers.go
> +		h.logger.Errorf("Ping error: %w", err)
Используй лучше напрямую `*zap.SuggaredLogger`

2023-06-20 11:45 UTC, s-shpak commented on internal/metcoll/client.go
> +func retryHTTPrequest(f Func, req *http.Request, ss Sleeper) (*http.Response, error) {
Да, ты прав, подменять методы плохо, когда они не несут нового функционала. Не делай так. Если ты пишешь миддлвеар для логгирования, то при его инициализации передавай в конструктор логгер, который этот middlewear будет использовать под капотом

2023-06-20 12:11 UTC, s-shpak commented on go.mod
Надо обновить

2023-06-20 12:11 UTC, s-shpak commented on internal/metcoll/client.go
> +	retryClient := retryablehttp.NewClient()
Согласно ТЗ:

- Количество повторов должно быть ограничено тремя дополнительными попытками.
- Интервалы между повторами должны увеличиваться: 1s, 3s, 5s.

Этого можно добиться переопределением `retryClient.Backoff`

2023-06-20 12:11 UTC, s-shpak commented on internal/stats/stats.go
> +		vm, err := mem.VirtualMemory()
Ну, при вызове `ReadMemStats` возвращается объект `MemStats`, в нем есть поле `Sys`, оно не является аналогом этого значения?

2023-06-20 12:20 UTC, s-shpak commented on internal/storage/database_storage.go
> +	pool, err := pgxpool.New(context.Background(), dataSourceName)
Используй здесь контекст, который ты передал в конструктор

2023-06-20 12:20 UTC, s-shpak commented on internal/storage/database_storage.go
> +	defer tx.Rollback(ctx)
Теперь ты откатишь транзакцию в любом случае, даже если ошибка не произошла. В defer надо поместить `tx.Commit(ctx)`, а при ошибке вызывать `Rollback`. Вызов `Commit` после `Rollback` ничего не ломает

2023-06-20 12:20 UTC, s-shpak commented on internal/storage/database_storage.go
> +		DO UPDATE SET value = $2 + (SELECT value FROM counters WHERE id = $1)
Не обязательно делать подзапрос, посмотри, что такое `EXCLUDED` и как получить значение `value`, из строки из-за которой произошел конфликт

2023-06-20 12:20 UTC, s-shpak commented on internal/handlers/handlers.go
> +		if err := m.Update(ctx, h.values); err != nil {
Это поведение автотестов в 13 инкременте?

2023-06-20 12:23 UTC, s-shpak requested changes

2023-06-20 12:23 UTC, s-shpak commented on internal/storage/database_storage.go
> +		retry.Delay(time.Duration(2*time.Second)),
Тут тоже последовательность ожидания должная быть 1s - 3s - 5s, можно также переопределить backoff

2023-06-20 12:31 UTC, ArtemShalinFe commented on internal/handlers/handlers.go
> +		if err := m.Update(ctx, h.values); err != nil {
Ага.

- Если я возвращаю обновленные метрики - то тесты сваливаются.
- Если ничего не возвращаю тоже сваливаются.
- Если возвращаю массив с ошибками, то считают что, что-то у меня что-то не работает и не пускают дальше.
- Если возвращаю пустой массив - то проходят.

2023-06-20 12:51 UTC, ArtemShalinFe commented on internal/handlers/handlers.go
> +	// Автотесты хотят, чтобы мы возвращали ошибку изменения каждой метрики
Вообще в "ТЗ" нет требований по возвращаемым ответам, однако, автотесты - "красные", если в принципе возвращаю что-то (массив измененных метрик, массив не измененных метрик и т.д.)

Вот на этой строке ошибка:
<img width="703" alt="image" src="https://github.com/ArtemShalinFe/metcoll/assets/54498127/d9fd2661-639a-43f2-958f-656f136d1ab1">

2023-06-20 13:04 UTC, ArtemShalinFe commented on internal/stats/stats.go
> +		vm, err := mem.VirtualMemory()
На сколько я понял из описания `Sys` - это количество байт, которое использует рантайм go. Наверно, в каком -то смысле подходит под `TotalMemory`.

В любом случае, в 15 инкременте добавляются эти метрики и в ТЗ явно просят использовать библиотеку `gopsutil`. 

p.S. Так и не понял, почему они внезапно появились в 12 инкременте... ну ладно.

2023-06-20 13:17 UTC, artemshalin commented on internal/metcoll/client.go
> +	retryClient := retryablehttp.NewClient()
Проглядел. Спасибо! Поправил.

2023-06-20 13:28 UTC, artemshalin commented on internal/handlers/handlers.go
> +		h.logger.Errorf("Ping error: %w", err)
Угу, вроде, понял идею. 👍

2023-06-20 13:55 UTC, artemshalin commented on internal/metcoll/client.go
> +func retryHTTPrequest(f Func, req *http.Request, ss Sleeper) (*http.Response, error) {
Поправил и надеюсь, что правильно понял идею:

- Если, например, есть несколько объектов, каждый со своим интерфейсом логирования, то правильным будет - разрабатывать свою структуру-композицию на основе выбранного в сервисе логгера. И уже у этой структуры делать методы требуемые для объекта.

2023-06-20 13:57 UTC, ArtemShalinFe commented on go.mod
Готово

2023-06-20 13:58 UTC, artemshalin commented on internal/storage/database_storage.go
> +	pool, err := pgxpool.New(context.Background(), dataSourceName)
поправил

2023-06-20 17:31 UTC, ArtemShalinFe commented on internal/storage/database_storage.go
> +		DO UPDATE SET value = $2 + (SELECT value FROM counters WHERE id = $1)
Прикольная фича постгреса. Спасибо 😄

2023-06-20 18:37 UTC, ArtemShalinFe commented on internal/handlers/handlers.go
> +	if _, err = w.Write(b); err != nil {
Пользователю уходит сообщение в формате `metric %s update error` без деталей. 
Ничего не отправлять - не могу, так написаны автотесты - описал ниже.

2023-06-20 19:01 UTC, ArtemShalinFe commented on internal/storage/database_storage.go
> +	defer tx.Rollback(ctx)
Угу, спасибо, исправил.

 🆘  Не смог понять чем плох `Rollback` после `Commit`? Вроде бы, ничего не ломает, не откатывает, если `Commit` уже был. Поясни, пожалуйста, почему именно подход (`Commit` после `Rollback`) более предпочтителен?

2023-06-20 19:02 UTC, ArtemShalinFe commented on internal/storage/database_storage.go
> +		retry.Delay(time.Duration(2*time.Second)),
Проглядел - поправил.

2023-06-20 19:14 UTC, ArtemShalinFe commented on cmd/agent/mock/main.go
Исправил, запомнил

2023-06-21 12:52 UTC, s-shpak commented on internal/handlers/handlers.go
> +		if err := m.Update(ctx, h.values); err != nil {
:(

2023-06-21 12:54 UTC, s-shpak commented on internal/storage/database_storage.go
> +	defer tx.Rollback(ctx)
My bad, мне казалось, что это может быть проблемой. Все ок!

2023-06-21 15:23 UTC, s-shpak commented on internal/metcoll/client.go
> +func retryHTTPrequest(f Func, req *http.Request, ss Sleeper) (*http.Response, error) {
Обычно в случае логгера нет смысла писать несколько типов с разными интерфейсами. Проще просто использовать тот функционал, который логгер предоставляет напрямую. Если логгер надо где-то использовать (например, в middleware), то используемый объект передается в middleware, которая сохраняет его и использует, когда это необходимо

2023-06-21 15:27 UTC, s-shpak requested changes

2023-06-21 15:27 UTC, s-shpak commented on internal/logger/app_logger.go
Давай все же переделаем использование логгера:

1. в main проинициализируй `zap.SuggaredLogger`
2. передавай его туда, где он необходим
3. например, в `NewLogger` (объект которого лучше назвать `LoggerMiddleware`, кстати), который сохранит его в своем внутреннем поле

2023-06-22 18:48 UTC, s-shpak approved these changes

2023-06-26 05:03 UTC, merged