Iter14
ArtemShalinFe/metcoll pull request #15
Opened 2023-06-26 07:43 UTC by ArtemShalinFe

2023-06-29 17:27 UTC, s-shpak requested changes

2023-06-29 17:27 UTC, s-shpak commented on cmd/agent/main.go
> +	rl, err := logger.NewRLLogger(sl)
Я не вижу смысла определять новый тип логгера, используй напрямую `zap.SuggaredLogger`

2023-06-29 17:27 UTC, s-shpak commented on internal/stats/stats.go
> +		go func() {
А зачем каждый раз стартовать новую горутину? Достаточно продолжать собирать метрики по истечению таймаута - разница в том, что в этом спринте это происходит независимо от других событий

2023-06-29 17:27 UTC, s-shpak commented on internal/stats/stats.go
> +		go func() {
см. комментарий выше

2023-06-29 17:27 UTC, s-shpak commented on internal/stats/stats.go
> +		go func() {
см. комментарий выше

2023-06-29 17:27 UTC, s-shpak commented on cmd/agent/main.go
> +			go client.UpdateMetric(ctx, ms, prs)
Почему бы всегда не использовать `BatchUpdate` ?

2023-06-29 17:27 UTC, s-shpak commented on internal/configuration/configuration.go
> +	flag.StringVar(&c.Key, "k", "", "hash key")
Что если ключ содержит непечатные символы?

2023-06-29 17:27 UTC, s-shpak commented on internal/handlers/handlers.go
> +	addHashHeader(w, []byte(resp))
Было бы хорошо делать это в middleware

2023-06-29 17:27 UTC, s-shpak commented on internal/stats/stats.go
> +			case ms <- mcs:
А что если канал будет забит?

2023-07-03 08:08 UTC, ArtemShalinFe commented on cmd/agent/main.go
> +	rl, err := logger.NewRLLogger(sl)
Не получается поправить. 
Тип используется для логов библиотеки `github.com/hashicorp/go-retryablehttp`, а ее логера другие интерфейсы, которые не совпадают с интерфейсами `zap`.

2023-07-03 08:08 UTC, ArtemShalinFe commented on internal/stats/stats.go
> +		go func() {
Спасибо, поправил.

2023-07-03 08:08 UTC, ArtemShalinFe commented on internal/stats/stats.go
> +		go func() {
Спасибо, поправил.

2023-07-03 08:08 UTC, ArtemShalinFe commented on internal/stats/stats.go
> +		go func() {
Спасибо, поправил.

2023-07-03 08:09 UTC, ArtemShalinFe commented on internal/configuration/configuration.go
> +	flag.StringVar(&c.Key, "k", "", "hash key")
Не подумал про это. 
Добавил удаление непечатных символов.

2023-07-03 08:24 UTC, ArtemShalinFe commented on cmd/agent/main.go
> +			go client.UpdateMetric(ctx, ms, prs)
Не указано, что делать, если `cfg.Limit = 0`, мне показалось логичным в этом случае использовать пакетное обновление метрик. Да и уж очень хотелось попробовать паттерн worker pool из совета ТЗ. 😄 

Так же не совсем понятно как ограничить количество одновременно исходящих запросов сверху с `BatchUpdate`, он же подразумевает 1 запрос...

2023-07-03 08:25 UTC, ArtemShalinFe commented on internal/handlers/handlers.go
> +	addHashHeader(w, []byte(resp))
Перенес в middleware

2023-07-03 10:56 UTC, ArtemShalinFe commented on internal/stats/stats.go
> +			case ms <- mcs:
В случае, если канал забит, будет ожидание, а потом отправим уже не актуальные данные.

Добавил только в этом месте `select default:`, в других, на мой взгляд, он не нужен.

2023-07-03 12:05 UTC, ArtemShalinFe commented
Переделал gracefull shutdown.

2023-07-04 05:47 UTC, s-shpak commented on cmd/agent/main.go
> +	rl, err := logger.NewRLLogger(sl)
понял, ок

2023-07-04 05:55 UTC, s-shpak commented on cmd/agent/main.go
> +			go client.UpdateMetric(ctx, ms, prs)
Инициатива - это круто :) Но отправка батчем не противоречить использованию workerpool'а, хотя это немного сложнее тестировать.

Представь себе, что отправление метрик занимает 5 секунд, запрос на отправление метрик прилетает каждую секунду, а `Limit = 3`. Тогда тебе нужно ограничивать количество запросов.

Согласен по `cfg.Limit`, в ТЗ не указано. Я предложу тебе либо не покрывать этот случай (возвращать ошибку, что параметр неверен), либо включить отправку поодиночке в этом случае. Но по умолчанию советую отправлять батчем - так ты сильно упростишь код.

Еще небольшой совет на будущее (если позволишь): если при выполнении какого-нибудь тестового задания перед тобой будет стоять выбор реализовать что-то просто и лаконично, или усложнить реализацию, чтобы продемонстрировать навыки, то выбирай (практически всегда, за редчайшим исключением) первое - собеседущие ждут, скорее всего, именно этого. Естественно, это не относится к Практикуму - тут как раз поле для экспериментов :)

2023-07-04 05:57 UTC, s-shpak commented on internal/configuration/configuration.go
> +	flag.StringVar(&c.Key, "k", "", "hash key")
Не, так не надо, это же ключ.

Ключ в реальном мире вполне может (и скорее всего будет) содержать непечатные символы. В ТЗ не оговаривается, как такой ключ будет передаваться в программу. Например, он может быть закодирован в base64 или hex, но нам это не так важно. Важно сейчас начать хранить ключ не в виде строки, а в виде слайса байтов: тогда при переходе на другой способ передачи ключа, твоя программа будет к нему уже готова.

2023-07-04 05:58 UTC, s-shpak commented on internal/stats/stats.go
> +			case ms <- mcs:
Да, это достаточное решение - мы можем просто дропнуть метрики, т.к. они, скорее всего, перестанут быть актуальны к моменту отправки

2023-07-04 06:25 UTC, ArtemShalinFe commented on internal/configuration/configuration.go
> +	flag.StringVar(&c.Key, "k", "", "hash key")
Понял, принял.

2023-07-04 06:45 UTC, ArtemShalinFe commented on cmd/agent/main.go
> +			go client.UpdateMetric(ctx, ms, prs)
Угу, понял. Удалил лишнее. Добавил значение по умолчанию для `cfg.Limit`.

Советы всегда к месту, спасибо. :)

2023-07-06 10:32 UTC, s-shpak requested changes

2023-07-06 10:32 UTC, s-shpak commented on internal/configuration/configuration.go
> +	flag.StringVar(&c.Key, "k", "", "hash key")
Не стоит дублировать поле, хранящее ключ. Оставь лучше просто `Key`, который будет слайсом байтов. Если ханить два значения, то ты рискуешь тем, что они разъедутся. Ну и просто смысла дублировать это значение, в общем, нет

2023-07-06 16:36 UTC, ArtemShalinFe commented on internal/configuration/configuration.go
> +	flag.StringVar(&c.Key, "k", "", "hash key")
Согласен. Исправил.

2023-07-07 02:46 UTC, s-shpak approved these changes

2023-07-20 05:56 UTC, merged