add docs, benchs, lint
ArtemShalinFe/metcoll pull request #16
Opened 2023-08-21 14:03 UTC by ArtemShalinFe

fix lint errors

2023-08-21 18:35 UTC, ArtemShalinFe commented
Честно собирал и разбирал профили, но, что-то как сделать еще лучше не придумал. 😢

2023-08-22 14:12 UTC, s-shpak requested changes
1. Кажется, что профиль, который сейчас лежит в `profiles` - профиль памяти. В задании речь шла о профиле CPU. В любом случае добавь в README.md инструкции по тому, как генерировать профиль (какие команды запускать, как ты генерировал нагрузку и т.п.)
2. Также добавь, пожалуйста, инструкции по запуску docserver для твоего проекта

2023-08-23 11:49 UTC, ArtemShalinFe commented
Готово. Readme дополнил.

2023-08-25 15:57 UTC, s-shpak reviewed
LGTM!

2023-08-25 15:57 UTC, s-shpak approved these changes

2023-08-26 18:57 UTC, merged