add staticcheck, constraints, db storage mocks
ArtemShalinFe/metcoll pull request #17
Opened 2023-08-26 19:14 UTC by ArtemShalinFe

2023-09-04 12:50 UTC, ArtemShalinFe commented
Сергей, подскажи, пожалуйста.

Есть проблемка, которую я не понимаю. Когда я вызываю свои статиклинтер и передаю ему пути к пакетам, которые нужно проверить, он еще и проверяет файлы кешей. И там находит ошибки и, соответственно, ругается. Это вроде не код моего проекта, но я не понял, как отучить его (статиклинтер) туда смотреть...

Каких-то ключей, параметров, вроде бы нету. Или я не туда смотрю...

Например, когда пишу команду:
`cmd/staticlint/staticlint ./...`

Он мне пишет вот что:
```
/Users/artem/Library/Caches/go-build/a8/a8e10aabc6433bfca4173d1164528b4fb3759992c8c7f0339dd3bb5c8b4eb7c4-d:47:2: called os.Exit in the main function
/Users/artem/Library/Caches/go-build/0d/0d3e1e6ce9221282f140e2049916646c39967d5c1d56be3c9df4999e5ae7df60-d:51:2: called os.Exit in the main function
/Users/artem/Library/Caches/go-build/3a/3a78fb7ee4f5693afeb6c0cbd12c797800572cbf0f6134ff4eee37162293ea34-d:47:2: called os.Exit in the main function
/Users/artem/Library/Caches/go-build/ab/abe2c12ab9190af16370c007ceeb5d2922c8993e761e4ac2bf7c90939965d47b-d:69:2: called os.Exit in the main function
/Users/artem/Library/Caches/go-build/8d/8d6bc12e154d18e5848d18cce2a045a27a75702e3184a412d5ca39f7b58c9913-d:49:2: called os.Exit in the main function
/Users/artem/Library/Caches/go-build/1e/1ef2142d180d306204b9fd601a8eff7986225c98cb9b188ac5e18b7d3624b681-d:53:2: called os.Exit in the main function
/Users/artem/Library/Caches/go-build/61/614760f4f0f422603a47298664977e3cd7e6b16d831236f02424f1fc7012baa0-d:51:2: called os.Exit in the main function
/Users/artem/Library/Caches/go-build/2a/2a0e546ea85d3c88262279dd9202dba5ebcf12bc760139cb44c70e7cf4e3b07e-d:81:2: called os.Exit in the main function
```

В файлах плюс-минус однотипный код такого плана:
```Golang
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
        "os"


        "testing"
        "testing/internal/testdeps"


        _test "github.com/ArtemShalinFe/metcoll/internal/storage"


)

var tests = []testing.InternalTest{

        {"TestDB_createTables", _test.TestDB_createTables},

        {"TestDB_GetInt64Value", _test.TestDB_GetInt64Value},

        {"TestDB_GetFloat64Value", _test.TestDB_GetFloat64Value},

        {"TestDB_GetDataList", _test.TestDB_GetDataList},

        {"TestDB_AddInt64Value", _test.TestDB_AddInt64Value},

        {"TestDB_SetFloat64Value", _test.TestDB_SetFloat64Value},

        {"TestState_SaveLoad", _test.TestState_SaveLoad},

        {"TestFilestorage_Interrupt", _test.TestFilestorage_Interrupt},

        {"TestFilestorage_SetFloat64Value", _test.TestFilestorage_SetFloat64Value},

        {"TestFilestorage_AddInt64Value", _test.TestFilestorage_AddInt64Value},

        {"TestFilestorage_BatchAddInt64Value", _test.TestFilestorage_BatchAddInt64Value},

        {"TestFilestorage_BatchSetFloat64Value", _test.TestFilestorage_BatchSetFloat64Value},

        {"TestNewMemStorage", _test.TestNewMemStorage},

        {"TestMemStorage_GetFloat64Value", _test.TestMemStorage_GetFloat64Value},

        {"TestMemStorage_GetInt64Value", _test.TestMemStorage_GetInt64Value},

        {"TestMemStorage_GetDataList", _test.TestMemStorage_GetDataList},

        {"TestGetSetState", _test.TestGetSetState},

        {"TestInitStorage", _test.TestInitStorage},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {
        testdeps.ImportPath = "github.com/ArtemShalinFe/metcoll/internal/storage"
}



func main() {

        m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

        os.Exit(m.Run())

}
```

2023-09-05 07:21 UTC, s-shpak requested changes

2023-09-05 07:21 UTC, s-shpak commented on internal/build/build.go
> +const infoTemplate = "Build version: %s; Build date: %s; Build commit: %s;"
Мне не очень нравится объявление шаблона в одном месте и его использование в другом: при изменении одного, надо будет не забыть изменить другое. Как это можно было бы решить?

2023-09-05 07:21 UTC, s-shpak commented on internal/exitchecker/exitchecker_test.go
> +			t.Errorf("cannot create go files err: %v", err)
Если здесь произошла ошибка, то 1. можно завершить тест заранее 2. не нужно вызвать `cleanup()`, потому что с т.з. идиоматического кода, `cleanup` не должна гарантировано содержать валидную функцию

2023-09-05 07:21 UTC, s-shpak commented on golangci-lint/report.json
1. Кажется, что этот файл не обязательно пушить в репозиторий
2. Ты не хочешь исправлять эти замечания линтера? Если это так, то либо явно проигнорируй их в коде, либо поменяй конфигурацию линтера

2023-09-06 08:58 UTC, ArtemShalinFe commented on internal/build/build.go
> +const infoTemplate = "Build version: %s; Build date: %s; Build commit: %s;"
Поместил в функцию.

2023-09-06 08:58 UTC, ArtemShalinFe commented on internal/exitchecker/exitchecker_test.go
> +			t.Errorf("cannot create go files err: %v", err)
Ага, забыл про `return`

2023-09-06 09:02 UTC, ArtemShalinFe commented on golangci-lint/report.json
1. Добавил файл `report.json` в .gitignore. 
2. Не, просто их очень много и поэтому замечания от golangci-lint я исправляю по мере свободного времени.

2023-09-10 06:46 UTC, s-shpak approved these changes

2023-09-10 10:50 UTC, merged