Iter23
ArtemShalinFe/metcoll pull request #18
Opened 2023-09-14 07:31 UTC by ArtemShalinFe

2023-09-18 13:57 UTC, s-shpak requested changes

2023-09-18 13:57 UTC, s-shpak commented on Makefile
> +cryptokeys:
Не всегда утилита `openssl` может быть установлена на машине: добавь лучше небольшую Go-программу, которую можно вызвать для генерации ключей. Если чувствуешь в себе силы, то добавь в корень проекта `go.work`, в котором ты сможешь обозначить утилиту как отдельный проект (см. https://go.dev/doc/tutorial/workspaces)

2023-09-18 13:57 UTC, s-shpak commented on cmd/server/main.go
> +		zap.S().Fatalf("an occured fatal err: %w", err)
Если ты используешь `zap`, то лучше использовать его и в коде агента

2023-09-18 13:57 UTC, s-shpak commented on internal/compress/compress.go
> +						zap.S().Errorf("cannot close gzip reader, err: %w", err)
На будущее: иногда имеет смысл использовать не `S()` напрямую, а создавать отдельный логгер из корневого, чтобы иметь возможность добавлять в каждое сообщение логгера какую-то дополнительную информацию. Например, добавить имя компонента, который вызывает этот логгер.

Это сообщение можно зарезолвить

2023-09-18 13:57 UTC, s-shpak commented on internal/crypto/crypto.go
> +func Encrypt(publicKey []byte, msg []byte) ([]byte, error) {
Все выполнено согласно ТЗ, все ок.

На самом деле асимметричное шифрование не используется таким образом: дело в том, что оно медленное по сравнению с симметричным. Обычно используется вот это: https://en.wikipedia.org/wiki/Key_encapsulation_mechanism

Этот комментарий можно зарезолвить

2023-09-18 13:57 UTC, s-shpak commented on internal/crypto/crypto_test.go
> +	td := os.TempDir()
Я помечал бы тесты, работающие с файловой системой, отдельным build tag: юнит-тесты, строго говоря, не должны создавать состояния в ОС. Тем не менее тестировать такой функционал тоже нужно, потому удалять бы я эти тесты не стал, но добавил бы возможность их не запускать

2023-09-18 13:57 UTC, s-shpak commented on internal/metrics/metrics.go
> +			return nil, fmt.Errorf("an occured error when parse float for metric, err: %w", err)
```suggestion
			return nil, fmt.Errorf("an occured error when parse float for metric: %w", err)
```

2023-09-21 10:00 UTC, artemshalin commented on internal/crypto/crypto_test.go
> +	td := os.TempDir()
Отметил такие тесты тегами.

2023-09-21 10:01 UTC, ArtemShalinFe commented on cmd/server/main.go
> +		zap.S().Fatalf("an occured fatal err: %w", err)
Спасибо, проглядел.

2023-09-21 10:03 UTC, ArtemShalinFe commented on Makefile
> +cryptokeys:
Угу, согласен. Программку добавил.

2023-09-21 10:05 UTC, ArtemShalinFe commented on internal/crypto/crypto.go
> +func Encrypt(publicKey []byte, msg []byte) ([]byte, error) {
Спасибо.

2023-09-21 10:05 UTC, ArtemShalinFe commented on internal/compress/compress.go
> +						zap.S().Errorf("cannot close gzip reader, err: %w", err)
Спасибо.

2023-09-21 13:06 UTC, s-shpak approved these changes

2023-09-22 05:46 UTC, merged