add resolver IP and X-Real-IP header
ArtemShalinFe/metcoll pull request #19
Opened 2023-09-26 08:36 UTC by ArtemShalinFe

2023-10-03 17:59 UTC, ArtemShalinFe commented
Не успел тесты дописать. Отправил как есть.

2023-10-05 10:25 UTC, s-shpak requested changes

2023-10-05 10:25 UTC, s-shpak commented on proto/v1/metcoll.proto
1. Добавь, пожалуйста, комментарии к структурам здесь - они будут перенесены в код
2. Сгенерированные файлы лучше помещать отдельно от `.proto` файлов, лучше в тот пакет, который их использует
3. Имя пакета, соответственно, надо выставлять корректно, посмотри как это делается в документации

2023-10-05 10:25 UTC, s-shpak commented on proto/v1/metcoll.proto
> +  string ID = 1;
Посмотри официальный стайлгайд, чтобы понять, как лучше называть перменные: https://protobuf.dev/programming-guides/style/#message-field-names

TL/DR: ID -> id, MType -> type, поправь также в ` MetricListResponse`, пожалуйста

2023-10-05 10:25 UTC, s-shpak commented on internal/metcoll/grpc_client.go
> +	} else {
`else` здесь не нужен, и я бы поменял порядок проверок - это упростит код

2023-10-05 10:25 UTC, s-shpak commented on internal/metcoll/http_client.go
> +func localIP() string {
Я бы воспользовался этим вариантом: https://stackoverflow.com/a/37382208

2023-10-08 21:04 UTC, s-shpak approved these changes

2023-10-09 05:59 UTC, merged