Iter5
ArtemShalinFe/metcoll pull request #6
Opened 2023-05-05 12:28 UTC by ArtemShalinFe

2023-05-05 18:24 UTC, s-shpak requested changes

2023-05-05 18:24 UTC, s-shpak commented on .DS_Store
Этот файл лучше добавить в .gitignore

2023-05-05 18:24 UTC, s-shpak commented on .gitignore
> +*debug*bin
Не совсем понятно назначение этого правила для .gitignore, ты не мог бы пояснить, почему ты его добавил?

2023-05-05 18:24 UTC, s-shpak commented on build.sh
> +go build -buildvcs=false -C ./cmd/agent -o agent
Зачем ты выстовляешь `buildvcs` в `false` здесь?

2023-05-05 18:24 UTC, s-shpak commented on coverage.html
Зачем ты добавил этот файл в репозиторий? Если это для баджа, то стоит добавить и логику, для того, чтобы бадж показывать. Если пока логику добавить не получается, то не стоит этот файл пушить в репозиторий (но можно, например, добавить правило в Makefile, чтобы его генерировать)

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/main.go
> +	metcoll "github.com/ArtemShalinFe/metcoll/cmd/agent/internal/client"
Зачем ты переименовал этот пакет здесь?

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/main.go
> +	metrics "github.com/ArtemShalinFe/metcoll/cmd/agent/internal/stats"
Смотри вопрос выше

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/main.go
> +	"github.com/caarlos0/env/v8"
Это необязательно, просто предложение: мне нравится организовывать импорты в несколько групп. Обычно это:
- импорты из стандартной библиотеки
- импорты из сторонних библиотек
- импорты пакетов твоей организации
- локальные импорты

Каждая группа разделена новой строкой (также как ты отделил импорты из stdlib). Это просто предложение, обычно это работает неплохо

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/main.go
> +var conn *metcoll.Client
Я не вижу причины делать эту переменную глобальной, ты не мог бы объяснить, почему ты принял такое решение?

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/main.go
> +var lastReportPush time.Time
Я не вижу причины делать эту переменную глобальной, ты не мог бы объяснить, почему ты принял такое решение?

2023-05-05 18:24 UTC, s-shpak commented on build.sh
Лучше было бы создать Makefile

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/main.go
> +		log.Fatal(err)
Это касается не только этой ошибки, но обработки ошибок в целом (надо поправить и в других местах).

Обычно в Go критические ошибки (которые не позволяют продолжить выполнение программы) возвращаются из функции и доходят до самого верхнего уровня (до функции main или, если речь идет об отдельной горутине, до функции которая была в ней запущена), где они логируются, и программа завершается.

Не стоит выходить из программы где-то в глубине логики:

Код сложнее читать, лучше, когда понятно, где именно точка выхода
Не получится завершить сторонние процессы штатным образом, что может привести к проблемам

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/main.go
> +	if *flagServer != "" {
Неверная логика: переменная окружения должна быть в приоритете по отношению к флагу

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/main_test.go
> +	lastReportPush = time.Now().Add(-1 * time.Hour)
Лучше используй значение из `cfg`

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/internal/client/client.go
Эту папку `internal` стоит перенести в `internal` в корне репозитория: в `cmd` должно лежать минимум логики, только для запуска приложения

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/internal/client/client.go
> +	log.Printf("Resp: [%d] [%s]\n", resp.StatusCode, string(userResult))
Если какая-то функция возвращает значение и ненулевую ошибку, то, как правило, значение считается невалидным и его не надо использовать (хотя, скорее всего, ты просто забыл выйти из функции ранее)

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/internal/client/client.go
> +		log.Print(err.Error())
Преобразовывать ошибку в строку не требуется - `log.Print` делает это автоматически

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/internal/stats/stats.go
> +	PollCount   int64
Это поле не обязательно делать экспортируемым

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/internal/stats/stats.go
> +	RandomValue int64 // timestamp
Это поле не обязательно делать экспортируемым

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/internal/stats/stats.go
> +	m := runtime.MemStats{}
Не обязательно каждый раз создавать новый объект, можно переиспользовать уже существующий

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/internal/stats/stats.go
> +	s.PollCount = s.PollCount + 1
Текст задания итерации сформулирован несколько некорректно, метрика `pollCount` на сервере должна отражать реальное количество операций сбора метрик, в текущей реализации это не так. Подумай, как это исправить

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/internal/stats/stats.go
> +	counterMetrics := make(map[string]string)
В Go переменные принято объявлять близко к тому месту, где они используются

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/internal/stats/stats.go
> +	gaugeMetrics["Alloc"] = fmt.Sprintf("%v", s.memStats.Alloc)
`strconv.FormatInt` (или `FormatFloat`) более производительна чем `fmt.Sprintf`:  https://gist.github.com/evalphobia/caee1602969a640a4530 (бенч не идеальный, но показательный)

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/internal/stats/stats_test.go
> +func requiredGaugeMetrics() [28]string {
Лучше не использовать массивы в данном случае: это тест, можно прненебречь выигрышем в производительности (если он есть), но реакторить тесты становится сложнее. [Premature optimization is the root of all evil](https://m.xkcd.com/1691/)

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/internal/stats/stats_test.go
> +func TestStats_Update(t *testing.T) {
Было бы неплохо проверить, что случайное значение тоже меняется

2023-05-05 18:24 UTC, s-shpak commented on cmd/agent/internal/stats/stats.go
> +type Stats struct {
Лучше добавить конструктор, т.к. это позволит не забыть проинициализировать `memStats`

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/main.go
> +	fmt.Printf("Try running on %v\n", cfg.Address)
Лучше использовать `log`

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/main.go
> +	r := h.ChiRouter()
1. Пакеты не стоит переименовывать просто так
2. Короктие переменные обычно исползуются для имен переменных, то что ты переименовал пакет, присвоив ему такой кортокий псевдоним, немного смущает

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/main.go
> +		panic(err)
Не надо паниковать без причины, лучше используй `log.Fatal`

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/main.go
> +	err := http.ListenAndServe(cfg.Address, r)
Вопрос стиля, но почему бы не:

```suggestion
	if err := http.ListenAndServe(cfg.Address, r); err != nil {
```

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/main_test.go
> +	parseConfig()
Если тестировать нечего, то лучше удали этот тест: сейчас это deadcode

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/internal/handlers/handlers.go
Смотри выше комментарий про `internal` агента

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/internal/handlers/handlers.go
> +	MemStorage "github.com/ArtemShalinFe/metcoll/internal/storage"
1. Имена пакетов в Go начинаются со строчной буквы
2. Нет смысла переименовывать пакет

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/internal/handlers/handlers.go
> +	http.Error(w, "Not implemented", http.StatusNotImplemented)
В Инкременте 1 просят возвращать `http.StatusBadRequest`

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/internal/handlers/handlers.go
> +func isGaugeMetric(r *http.Request) bool {
Кажется, что создавать отдельную функцию на каждый тип - overkill, может сделать как-нибудь по-другому?

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/internal/handlers/handlers.go
> +func counterHandler(w http.ResponseWriter, r *http.Request) {
Я бы вынес логику обработки `payload`'а запроса в отдельную функцию, т.к. сейчас функцию `counterHandler` делает несколько вещей: и извелкает параметры из запроса, и работает с тем, чтобы записать ответ HTTP клиенту, и вычисляет этот ответ. Хорошим тоном (не только в Go) считается делать функции, которые выполняют какое-то одно логическое действие.

Этот комментарий касается и `gaugeHandler`

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/internal/handlers/handlers.go
> +	if strings.TrimSpace(k) == "" {
Не совсем понимаю логику этой проверки, ты мог бы пояснить, пожалуйста?

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/internal/handlers/handlers.go
> +func metricName(r *http.Request) string {
Не стоит оборачивать вызов функции в функцию

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/internal/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Обычно клиенту не стоит возвращать сырое сообщение об ошибке. Клиенту лучше объяснить (хотя это тоже необязательно, точно не в этом спринте), что именно произошло

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/internal/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
И клиенту точно не надо объяснять, почему на сервере произошла ошибка, т.к. эта создает риск того, что клиент будет эксплуатировать эту проблему. А вот залогировать ее стоит

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/internal/handlers/handlers.go
> +	MemStorage.Values.SetInt64Value(k, newValue)
Здесь ты забыл проверить возвращаемую ошибку

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/internal/handlers/handlers.go
> +	io.WriteString(w, fmt.Sprintf("%s %v", k, newValue))
Можно использовать просто `w.Write`, ошибку тоже надо проверить

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/internal/handlers/handlers.go
> +func gaugeHandler(w http.ResponseWriter, r *http.Request) {
Сотри комментарии к `counterHandler`

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/internal/handlers/handlers.go
> +	body := `
Это делать необязательно, просто для информации: в стандартной библиотеке Go для формирования HTML-страниц есть пакет `html/template`

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/internal/handlers/handlers.go
> +		have := MemStorage.Values.StorageHaveMetric(metricName)
А что делать, если метрика удалится после этого вызова, но до вызова на строке 58? На самом деле, это вопрос о том, стоит ли вообще определять отдельный метод для проверки существования метрики (может это делать где-то в другом месте?)

2023-05-05 18:24 UTC, s-shpak commented on cmd/server/internal/handlers/handlers.go
> +	if isGaugeMetric(r) {
В ветвях `if` много повторений кода, некоторые части можно вынести до и после этого `if`

2023-05-05 18:24 UTC, s-shpak commented on internal/storage/storage.go
> +	Data map[string]interface{}
1. Это поле необязательно делать экспортируемым
2. Что произойдет, если мы одновременно попытаемся прочитать и записать значение? Как этого избежать?

2023-05-05 18:24 UTC, s-shpak commented on internal/storage/storage.go
> +var ErrWrongType = errors.New("wrong value type")
Эта ошика не используется нигде, кроме этого пакета, ее не надо делать экспортируемой

2023-05-05 18:24 UTC, s-shpak commented on internal/storage/storage.go
> +	switch v.(type) {
Здорово, что ты знаешь о `type switch`, но здесь он не треубется: намного проще сделать type assertion: `v, ok := ms.Data[key].(int64)`

2023-05-05 18:24 UTC, s-shpak commented on internal/storage/storage.go
> +func init() {
Нет смысла делать `Values` глобальным, проинициализируй его внутри функции и передавай туда, где он используется

2023-05-09 07:09 UTC, ArtemShalinFe commented on .gitignore
> +*debug*bin
Это чтобы не пушить бинари, а то у меня бывает, что я, находясь в отладке, могу что-то запушить в репозиторий. Вот например:

<img width="391" alt="image" src="https://user-images.githubusercontent.com/54498127/237020606-242cec02-7de8-474c-8930-3298af2ead82.png">

Не знаю можно как-то по-другомоу это сделать или нет)

2023-05-09 07:22 UTC, artemshalin commented on build.sh
> +go build -buildvcs=false -C ./cmd/agent -o agent
В CI стоит этот флаг, я подумал, что для полной идентичности нужно тоже поставить, перед тем как запускать тесты локально.

2023-05-09 07:26 UTC, ArtemShalinFe commented on coverage.html
Забыл в .gitignore включить его.

Добавил.

2023-05-09 07:30 UTC, ArtemShalinFe commented on cmd/agent/main.go
> +	metcoll "github.com/ArtemShalinFe/metcoll/cmd/agent/internal/client"
Если не переименовывать, то в коде будет обращение: `client.Client`, на сколько я понимаю, это не красиво и не приветствуется.

Сейчас понимаю, что правильнее было бы пакет называть не client, а metcoll.

- [ ] Переименовать пакет client в metcoll.

2023-05-09 07:31 UTC, ArtemShalinFe commented on cmd/agent/main.go
> +	metrics "github.com/ArtemShalinFe/metcoll/cmd/agent/internal/stats"
- [ ] Переименовать пакет stats в  metrics

2023-05-09 07:39 UTC, ArtemShalinFe commented on cmd/agent/main.go
> +	"github.com/caarlos0/env/v8"
Спасибо, возьму в привычку подобную практику.

2023-05-09 07:52 UTC, artemshalin commented on cmd/agent/main.go
> +var conn *metcoll.Client
Да, наверно, можно использовать ее только в main.

2023-05-09 07:52 UTC, ArtemShalinFe commented on cmd/agent/main.go
> +var lastReportPush time.Time
Да, наверно, можно использовать ее только в main.

2023-05-10 07:34 UTC, ArtemShalinFe commented on build.sh
Согласен. Спасибо.

2023-05-10 09:55 UTC, ArtemShalinFe commented on cmd/server/internal/handlers/handlers.go
> +	if strings.TrimSpace(k) == "" {
В задании просто написано, что обрабатывать все пограничные случаи. Запрос с пустой метрикой я посчитал одним из таких.

2023-05-10 11:20 UTC, ArtemShalinFe commented on internal/storage/storage.go
> +	Data map[string]interface{}
Добавить мьютекс в структуру. Блокировать значение перед чтением/записью.
Не думал, что это важно на этой стадии.

2023-05-10 11:21 UTC, ArtemShalinFe commented on internal/storage/storage.go
> +var ErrWrongType = errors.New("wrong value type")
Исправил логику работы с хранилищем. Ошибку удалил.

2023-05-10 19:00 UTC, ArtemShalinFe commented on cmd/server/internal/handlers/handlers.go
> +func isGaugeMetric(r *http.Request) bool {
исправил через интерфейсы

2023-05-10 19:03 UTC, ArtemShalinFe commented on cmd/server/internal/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Исправил

2023-05-10 19:04 UTC, ArtemShalinFe commented on cmd/server/internal/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
исправил

2023-05-10 19:04 UTC, ArtemShalinFe commented on cmd/server/internal/handlers/handlers.go
> +	MemStorage.Values.SetInt64Value(k, newValue)
Исправлена логика работы с хранилищем

2023-05-10 19:04 UTC, ArtemShalinFe commented on cmd/server/internal/handlers/handlers.go
> +	io.WriteString(w, fmt.Sprintf("%s %v", k, newValue))
Исправлена логика работы с хранилищем

2023-05-10 19:05 UTC, ArtemShalinFe commented on cmd/server/internal/handlers/handlers.go
> +		have := MemStorage.Values.StorageHaveMetric(metricName)
Исправлена логика работы с хранилищем. добавлен мьютекс

2023-05-10 19:05 UTC, ArtemShalinFe commented on cmd/server/internal/handlers/handlers.go
> +	if isGaugeMetric(r) {
Сделал рефакторинг

2023-05-10 19:05 UTC, artemshalin commented on internal/storage/storage.go
> +func init() {
Исправил

2023-05-10 19:08 UTC, ArtemShalinFe commented on cmd/agent/internal/stats/stats.go
> +	s.PollCount = s.PollCount + 1
Если правильно понял, то исправил.

2023-05-11 16:04 UTC, s-shpak commented on cmd/agent/main.go
> +	metcoll "github.com/ArtemShalinFe/metcoll/cmd/agent/internal/client"
Я, кстати, не вижу проблем в обращении `client.Client`

2023-05-11 16:08 UTC, s-shpak commented on cmd/agent/internal/stats/stats.go
> +	s.PollCount = s.PollCount + 1
Теперь ты собираешь количество отправлений данных на сервер, а не количество обновления метрик

2023-05-11 16:09 UTC, s-shpak commented on cmd/agent/internal/stats/stats.go
> +	gaugeMetrics["Alloc"] = fmt.Sprintf("%v", s.memStats.Alloc)
В коде есть еще несколько мест, где вместо `strconv` ты используешь `fmt`

2023-05-11 16:12 UTC, s-shpak commented on cmd/server/main.go
> +	err := http.ListenAndServe(cfg.Address, r)
Это не единственное место, где `err` можно было бы обернуть в `if`. Это не только, кстати, вопрос стиля, но и вопрос области видимости переменной с ошибкой, которую ты создаешь. Ну и в целом лучше придерживаться единного стиля

2023-05-11 16:35 UTC, s-shpak requested changes
Я переоткрыл некоторые комментарии из прошлого ревью. На будущее: не резолвь, пожалуйста, комментарии, это задача ревьюера

2023-05-11 16:35 UTC, s-shpak commented on cmd/agent/main.go
> +				t := fmt.Sprintf("cannot push %s %s with value %s on server: %v", mType, name, value, err)
Почему бы просто не использовать `fmt.Errorf` ?

2023-05-11 16:35 UTC, s-shpak commented on cmd/agent/main.go
> +	flagServer := flag.String("a", "localhost:8080", "server end point")
Стилистическое, но вместо инициализаций новых переменных я бы записывал значения сразу в объявленную структуру

2023-05-11 16:35 UTC, s-shpak commented on cmd/agent/main.go
> +		time.Sleep(time.Duration(cfg.PollInterval) * time.Second)
Нет смысла пересчитывать интервал каждый раз, проинициализирую его выше: `pollInterval := time.Duration(cfg.PollInterval) * time.Second` или вообще объяви тип поля в объекте конфигурации как `time.Duration` (но в этом случае не парси напрямую, автотесты все равно будут передавать флагами `int`)

2023-05-11 16:35 UTC, s-shpak commented on cmd/agent/main_test.go
> +		t.Run(tt.name, func(t *testing.T) {
Я рекоммендую привыкнуть переопределять переменные из цикла внутри этого цикла для тестов (в данном случае `tt := tt`). Это особенно важно для тестов, т.к. тесты часто запускаются параллельно, а в этом случае возможны проблемы: https://eli.thegreenplace.net/2019/go-internals-capturing-loop-variables-in-closures/

2023-05-11 16:35 UTC, s-shpak commented on internal/handlers/handlers.go
> +	k := chi.URLParam(r, "metricName")
Мне не очень нравится то, что эта функция знае о том, какой роутер ты используешь: в идеале если мы заменим `chi` функция не должна сломаться, потому что это не должно повлиять на бизнес-логику

2023-05-11 16:35 UTC, s-shpak commented on internal/handlers/handlers.go
> +	values = storage.NewMemStorage()
Это те же глобальные переменные только спрятанные, `init()` тоже лучше не использовать без надобности

2023-05-11 16:35 UTC, s-shpak commented on internal/storage/storage.go
> +	v, ok := ms.data[key].(int64)
Мьютексом надо защищать и операции чтения

2023-05-11 16:35 UTC, s-shpak commented on internal/storage/storage.go
> +	ms.Unlock()
Лучше добавь `defer ms.Unlock()` после строки 36

2023-05-11 16:35 UTC, s-shpak commented on internal/storage/storage.go
> +	data map[string]interface{}
1. Пустые интерфейсы теперь принято называть `any`
2. Я бы создал два хранилища - одно для gauge, другое для counter. Операции преобразования интерфейса в конкретные значения дорогостоящие

2023-05-11 16:35 UTC, s-shpak commented on internal/storage/storage.go
> +	return ms.data
Нужно ли здесь возвращать интерфейсы? Если хочешь простое решение, то можно сразу возвращать строки. Можно сложнее, но тогда надо возвращать что-то типа интерфейса `Stringer`

2023-05-11 16:35 UTC, s-shpak commented on .DS_Store
.DS_store надо удалить из репозитория

2023-05-11 16:35 UTC, s-shpak commented on makefile
`Makefile` именуют обычно с заглавной буквы: https://stackoverflow.com/questions/14368941/is-the-convention-for-naming-make-files-to-use-a-capital-m-such-as-makefile

2023-05-15 07:18 UTC, ArtemShalinFe commented on cmd/agent/internal/stats/stats.go
> +	gaugeMetrics["Alloc"] = fmt.Sprintf("%v", s.memStats.Alloc)
Нашел, заменил.

2023-05-15 07:23 UTC, ArtemShalinFe commented on cmd/server/main.go
> +	err := http.ListenAndServe(cfg.Address, r)
Заменил, где нашел.

2023-05-15 07:26 UTC, artemshalin commented on cmd/agent/main.go
> +				t := fmt.Sprintf("cannot push %s %s with value %s on server: %v", mType, name, value, err)
Точно. Поправил.

2023-05-15 07:43 UTC, artemshalin commented on cmd/agent/main.go
> +		time.Sleep(time.Duration(cfg.PollInterval) * time.Second)
Поправил.

2023-05-15 07:48 UTC, artemshalin commented on cmd/agent/main_test.go
> +		t.Run(tt.name, func(t *testing.T) {
Спасибо. Поправил.

2023-05-15 07:48 UTC, ArtemShalinFe commented on internal/storage/storage.go
> +	v, ok := ms.data[key].(int64)
Поправил.

2023-05-15 07:49 UTC, artemshalin commented on internal/storage/storage.go
> +	ms.Unlock()
Исправил везде

2023-05-15 07:50 UTC, ArtemShalinFe commented on makefile
Переименовал

2023-05-15 07:51 UTC, ArtemShalinFe commented on .DS_Store
Удалил.

2023-05-15 07:55 UTC, ArtemShalinFe commented on cmd/agent/main.go
> +	flagServer := flag.String("a", "localhost:8080", "server end point")
Угу, кода стало меньше. Спасибо.

2023-05-15 09:49 UTC, ArtemShalinFe commented on cmd/agent/internal/stats/stats.go
> +	s.PollCount = s.PollCount + 1
Добавил обнуление `s.PollCount` после успешной отправки на сервер.

2023-05-15 10:05 UTC, ArtemShalinFe commented on internal/storage/storage.go
> +	return ms.data
Исправил на массив строк

2023-05-15 10:05 UTC, ArtemShalinFe commented on internal/storage/storage.go
> +	data map[string]interface{}
Исправил на два хранилища

2023-05-15 12:33 UTC, ArtemShalinFe commented on internal/handlers/handlers.go
> +	k := chi.URLParam(r, "metricName")
вынес код, обрабатывающий бизнес-логику, в отдельные функции

2023-05-15 12:34 UTC, ArtemShalinFe commented on internal/handlers/handlers.go
> +	values = storage.NewMemStorage()
Поправил

2023-05-15 13:11 UTC, artemshalin commented on cmd/agent/main.go
> +	flagServer := flag.String("a", "localhost:8080", "server end point")
Спасибо, так лучше, исправил.

2023-05-16 21:31 UTC, s-shpak commented on makefile
Мне кажется, не переименовал

2023-05-16 21:49 UTC, s-shpak requested changes

2023-05-16 21:49 UTC, s-shpak commented on cmd/agent/main.go
> +	var lastReportPush time.Time
Ты забыл обновлять lastReportPush

2023-05-16 21:49 UTC, s-shpak commented on cmd/agent/main.go
> +			s.ClearPollCount()
Это хрупко - непонятно, улетел ли PollCount на сервер или нет, это же не транзакция. Перенеси его лучше в `pushReport` и зануляй, если это значение дествительно ушло на сервер

2023-05-16 21:49 UTC, s-shpak commented on cmd/agent/main.go
> +	return now.After(lastReportPush.Add(time.Second * time.Duration(reportInterval)))
Нет смысла пересчитывать интервал каждый раз, проинициализирую его выше

2023-05-16 21:49 UTC, s-shpak commented on internal/handlers/handlers.go
> +			http.Error(w, "Internal server error", http.StatusInternalServerError)
internal server errors лучше логировать

2023-05-16 21:49 UTC, s-shpak commented on internal/handlers/handlers.go
> +	w.Write([]byte(fmt.Sprintf("%s %v", k, newValue)))
Я рекоммендую привыкать обрабатывать все возможные ошибки. `w.Write` может вернуть ошибку. Это можно обрабатывать по-разному, пока достаточно залогировать факт возникновения ошибки

2023-05-16 21:49 UTC, s-shpak commented on internal/handlers/handlers.go
> +			http.Error(w, "Internal server error", http.StatusInternalServerError)
internal server errors лучше логировать

2023-05-16 21:49 UTC, s-shpak commented on internal/handlers/handlers.go
> +	_, err = w.Write([]byte(value))
стилистическое: я бы обернул ошибку так:

```suggestion
	if _, err = w.Write([]byte(value)); err != nil {
	...
	}
```

2023-05-16 21:49 UTC, s-shpak commented on internal/handlers/handlers.go
> +		log.Printf("getMetric error: %v", err)
Пока это подойдет, но в следующем спринте надо будет менять (главное мне не забыть об этом :) )

2023-05-16 21:49 UTC, s-shpak commented on internal/handlers/handlers.go
> +	value, have := m.Get(h.values, metricName)
стилистическое: обычно в Go переменная для проверки существования называется `ok`

2023-05-16 21:49 UTC, s-shpak commented on internal/storage/storage.go
> +func (ms *MemStorage) GetCounterList() []string {
это надо защитить мьютексом

2023-05-16 21:49 UTC, s-shpak commented on internal/storage/storage.go
> +func (ms *MemStorage) GetGaugeList() []string {
это надо защитить мьютексом

2023-05-17 07:06 UTC, ArtemShalinFe commented on cmd/agent/main.go
> +	return now.After(lastReportPush.Add(time.Second * time.Duration(reportInterval)))
Исправил, спасибо.

2023-05-17 07:08 UTC, artemshalin commented on internal/handlers/handlers.go
> +	value, have := m.Get(h.values, metricName)
Исправил, спасибо.

2023-05-17 07:09 UTC, ArtemShalinFe commented on internal/storage/storage.go
> +func (ms *MemStorage) GetCounterList() []string {
Исправил, спасибо.

2023-05-17 07:09 UTC, ArtemShalinFe commented on internal/storage/storage.go
> +func (ms *MemStorage) GetGaugeList() []string {
Исправил, спасибо.

2023-05-17 07:14 UTC, artemshalin commented on internal/handlers/handlers.go
> +			http.Error(w, "Internal server error", http.StatusInternalServerError)
Добавил логирование.

2023-05-17 07:14 UTC, ArtemShalinFe commented on internal/handlers/handlers.go
> +			http.Error(w, "Internal server error", http.StatusInternalServerError)
Добавил логирование.

2023-05-17 07:26 UTC, artemshalin commented on cmd/agent/main.go
> +	var lastReportPush time.Time
Спасибо. Поправил.

2023-05-17 07:26 UTC, ArtemShalinFe commented on cmd/agent/main.go
> +			s.ClearPollCount()
Угу, согласен. Перенес.

2023-05-17 07:35 UTC, ArtemShalinFe commented on makefile
теперь точно переименовал 😄

2023-05-17 07:46 UTC, artemshalin commented on cmd/agent/internal/stats/stats.go
> +	gaugeMetrics["Alloc"] = fmt.Sprintf("%v", s.memStats.Alloc)
Не могу найти больше мест где используется `fmt` вместо `strconv`.

2023-05-17 07:47 UTC, ArtemShalinFe commented on cmd/server/main.go
> +	err := http.ListenAndServe(cfg.Address, r)
Прошелся по коду, на мой взгляд мест больше нет, где можно было бы поправить.

2023-05-17 08:14 UTC, s-shpak commented on cmd/agent/main.go
> +			s.ClearPollCount()
Все еще хрупко: а если `PollCount` успел уйти на сервер, а другие метрики нет?

2023-05-17 09:30 UTC, ArtemShalinFe commented on cmd/agent/main.go
> +			s.ClearPollCount()
Поправил.

2023-05-17 10:06 UTC, s-shpak approved these changes
LGTM!

2023-05-18 08:44 UTC, merged